### ISSUE TITLE
problem with localhost and not 127.0.0.1 on Mac Catalina 10.15.5

### ISSUE THREAD

**Issue by jhtib** [lostisland/faraday#1200] opened 2020-11-06 00:13 UTC
## Basic Info

* Faraday Version: 0.9.2
* Ruby Version: 2.4.3

## Issue description
Please provide a description of the issue you're experiencing.
This is a strange issue and most likely reflects a user issue but might be some configuration value I'm unaware of. Apologies ahead of time, read through releases and didn't see mention of this.

When I use an in-house library that specifies localhost, it doesn't resolve but does when 127.0.0.1 - I know there can be differences but this seems really strange. I'm on a Mac and commented out the IPV6 line in /etc/hosts but still having issue.

Please also provide the exception message/stacktrace or any other useful detail.

Here's a sample screenshot:

![Screen Shot 2020-11-05 at 4 08 07 PM](https://user-images.githubusercontent.com/61478133/98310171-2829c380-1f81-11eb-8315-ac6465e082ab.png)

## Steps to reproduce
If possible, please provide the steps to reproduce the issue.
On Mac Catalina 10.15.5, make a call with Faraday to a localhost resource and see error out. The same call with 127.0.0.1 succeeds. Accessing resource via browser also succeeds.

**Comment by iMacTia** [comment] 2020-11-06 08:49
Hi @jhtib and sorry you're having issues with Faraday.
First of all, I wanted to understand if this was an issue with Faraday or a networking issue, because it definitely look strange.
To do so, I've taken up a Node.js server listening on port 3000, installed Faraday 0.9.2 and tried the following:

<img width="889" alt="Screenshot 2020-11-06 at 08 40 22" src="https://user-images.githubusercontent.com/2527520/98344823-b77bb900-200b-11eb-9b53-d3c9ebc46a02.png">

As you can see, I'm able to reach the service with both `localhost` and `127.0.0.1`, which is the expected behaviour.
Now, as per what could the actual reason be, you should probably check outside of Faraday.
Here are a few suggestions from me, although not having a clear picture of your local setup makes this mostly a guess:
* The service you're calling to is only listening on `127.0.0.1`. You can fix this by telling your service to listen on `0.0.0.0` (all sources). In `rails`, for example, you do this by starting your server with the `-b 0.0.0.0` option.
* The `/etc/hosts` file is messed up. Hardly the cause, but since you mentioned some changes to the hosts file, it might be worth reverting it back to its original state.
* There's something wrong with the application: can't really rule this out, it might be worth speaking with who developed the application and ask them to help debugging

I hope the suggestions above help, but for now I'd rule out an issue with Faraday and close this.
Please do let me know if you manage to solve this and if you find anything else pointing towards Faraday then I'll happily reopen 👍

**Closed by iMacTia** 2020-11-06 08:49 UTC
