### ISSUE TITLE
Header's first letter is automatically capitalized

### ISSUE THREAD

**Issue by Montaguti** [lostisland/faraday#747] opened 2017-11-16 12:04 UTC
Is there any way to avoid this? Cuz, i'm trying to consume an API that one header's name must be "apptoken".

`req.headers["apptoken"] = Rails.configuration.token_iss`

When I debbug it I can see that it is leaving as "apptoken", but when the other web service receives the request it is set as "Apptoken"...

Anyone has any idea why this could be happening? Is that a Faraday's issue/normalization?

**Comment by iMacTia** [comment] 2017-11-16 15:12
I don't believe we change headers anyway. That might be something the adapter is doing. Which one are you using?

To be honest, headers should always be capitalised according to the standard (I'm going by memory though, take it 90% sure).

**Comment by Montaguti** [comment] 2017-11-16 23:46
@iMacTia default adapter... Yeah, I agree that they should be capitalised. I also asked for the API's owners to fix it, and they did (so everything is fine now). But it take some time to realize what was going on cuz debugger was showing "apptoken" and the message from ws was always "invalid apptoken". 

Thanks for your time dude!

**Comment by iMacTia** [comment] 2017-11-17 08:38
Thanks for the update @Montaguti!
Glad to know everything is fine now.
The fact your debugger found the lowercase value but the server was receiving the capitalised one confirms that it was probably `Net::HTTP` the “culprit” here. 

Closing this then 👍

**Closed by iMacTia** 2017-11-17 08:38 UTC
Labels: unconfirmed

**Comment by iMacTia** [comment] 2017-11-28 13:58
For reference, we do have a class responsible for this: https://github.com/lostisland/faraday/blob/master/lib/faraday/utils.rb#L8

However I'm happy with the resolution here as headers are case-insensitive according to the [RFC7230](https://tools.ietf.org/html/rfc7230#section-3.2)

**Comment by yxhuvud** [comment] 2018-01-10 12:13
@iMacTia `-` is not really the upper-case version of `_` though, and `_` is allowed in header names nowadays, so this can still be an issue.

**Comment by iMacTia** [comment] 2018-01-16 16:26
@yxhuvud I understand there might be edge cases where you need to specify a particular unconventional header name. This issue was closed because @Montaguti said the issue was fixed server-side.
If you have a situation where you need Faraday to stop manipulating header names because a server-side fix is not possible, I've pointed to the "culprit" and I'm happy to review a PR that fixes that.
**The new behaviour should be, however, opt-in.**

**Comment by thisismydesign** [comment] 2018-11-13 13:46
@iMacTia I'm in the same situation. So just to double check, this behavior is coming from you, right? [Seems that way](https://github.com/lostisland/faraday/blob/88de44ebe3c40f9050553ce7c0018990b92c2f38/lib/faraday/utils.rb#L39-L49) to me.

IMO conventions should not be enforced here especially given the abstraction layer nature of Faraday. I think it at least should be documented. Would it make sense to open a more precise issue about it or reopen this one?

In any case, do you know of a workaround?

**Comment by thisismydesign** [comment] 2018-11-13 13:59
@iMacTia Also, I'm not familiar with RFC7230 but form the link you provided it doesn't seem like header key shouldn't contain an underscore. Am I missing something?

**Comment by yxhuvud** [comment] 2018-11-13 15:30
A workaround is to use raw Typheus instead, and specifying the headers using strings (symbols are autoformatted, just like in Faraday, but strings are not).

**Comment by thisismydesign** [comment] 2018-11-13 15:56
Thanks and also for the headsup. Although I'd imagine I can do this with other libs, was hoping for something in Faraday.

**Comment by iMacTia** [comment] 2018-11-19 11:37
@thisismydesign @yxhuvud @Montaguti 
I spent some more time on this over the past days and I can confirm this is an issue with the adapter, not Faraday.
To prove that, I first checked the `Faraday::Utils::Headers` implementation:

```ruby
require 'faraday'

headers = Faraday::Utils::Headers.new
headers[:accept] = 'application/json'
headers['appToken'] = 'token'
headers #=> {"Accept"=>"application/json", "appToken"=>"token"}
```

As you can see above (and you can check that in the `KeyMap` implementation), Faraday only converts headers when they are provided as symbols, not for strings.

So  after confirming `Faraday::Utils::Headers` were working as expected, I went on and checked `Net::HTTP`:

```ruby
uri = URI('http://www.sushi.com/index.php/nigiri')
req = Net::HTTP::Get.new(uri)
req['appToken'] = 'token'

http = Net::HTTP.new(uri.hostname, uri.port)
http.set_debug_output($stdout)
res = http.request(req)
#=> "GET /index.php/nigiri HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: Ruby\r\nHost: www.sushi.com\r\nApptoken: token\r\nConnection:close\r\n\r\n"
```

As you can see, the header was capitalised. After the culprit was identified (again) a quick Google search gave me the confirmation: https://stackoverflow.com/questions/8864627/how-do-i-preserve-case-with-http-get

**Comment by thisismydesign** [comment] 2018-11-19 12:02
@iMacTia Thanks for verifying.

> Faraday only converts headers when they are provided as symbols, not for strings.

So it is not the case after all that `Net::HTTP` is the sole culprit.

See:
```
require 'faraday'

headers = Faraday::Utils::Headers.new
headers[:bla_bla] = 'token'
headers => {"Bla-Bla"=>"token"}
```

But fair enough, at least there seems to be a workaround when using the right adapter.

**Comment by yxhuvud** [comment] 2018-11-19 12:49
@iMacTia So in other words, you claim that it should work if using typhoues as an adapter? Because not rewriting strings is also the behaviour that library has. 

Also note that as per the relevant RFC, capitalization is perfectly ok as the standard says capitalization doesn't matter. It is the rewriting of `-` to `_` that is questionable.

(In my particular case the server was not standards compliant to capitalizing alphabetic characters, but I think noone is claiming Faraday should be able to produce headers that isn't compliant at all)

**Comment by iMacTia** [comment] 2018-11-19 13:03
@thisismydesign yeah you're right, my post above assumes you use strings as the name headers if you want to control the casing. If you use symbols then the standard will be enforced. At least this provides both functionalities 👍 

@yxhuvud I haven't checked Typhoeus, I only checked Net::HTTP. I just ensured that Faraday is not converting header names when using strings as keys. If you do use string keys for your headers and you still experience the conversion with other adapters, then that could mean they're doing the same conversion os Net::HTTP. You'll need to check the adapter code to double-check though as I checked Net::HTTP code.

**Comment by liedergram** [comment] 2020-12-01 21:29
I'm pasting here some stuffs if anyone gets into the issue and does not see before his eyes.
Ruby itself makes assumptions on whether you provide a string or a key:

```ruby
require 'faraday'

f = Faraday.new("http://google.fr", headers: { 'TAB': 1, 'ula': 2, rasa: 3, Itou: 4})
puts "f: #{f.headers}"

g = Faraday.new("http://google.fr") do |g|
    g.headers['TAB'] = 1
    g.headers['ula'] = 2
    g.headers[:rasa] = 3
    g.headers[:Itou] = 4
end
puts "g: #{g.headers}"

headers_h = { 'TAB' => 1, 'ula' => 2, :rasa => 3, :Itou => 4}
h = Faraday.new("http://google.fr", headers: headers_h)
puts "h: #{h.headers}"
```

```bash
liedergram@Desktop-Home:~$ ruby testfaradaycapitalization.rb
f: {"Tab"=>1, "Ula"=>2, "Rasa"=>3, "Itou"=>4, "User-Agent"=>"Faraday v1.1.0"}
g: {"TAB"=>1, "ula"=>2, "Rasa"=>3, "Itou"=>4, "User-Agent"=>"Faraday v1.1.0"}
h: {"TAB"=>1, "ula"=>2, "Rasa"=>3, "Itou"=>4, "User-Agent"=>"Faraday v1.1.0"}
```
