### ISSUE TITLE
NoMethod Error Given When URL is not formatted properly

### ISSUE THREAD

**Issue by gardnerapp** [lostisland/faraday#1346] opened 2021-12-14 15:16 UTC
## Basic Info

* Faraday Version: 1.8
* Ruby Version: 3.0.2

## Issue description

When an improper URL is passed to an HTTP verb method the following error is raised: 
```NoMethodError (undefined method `include?' for nil:NilClass```

## Steps to reproduce
```ruby
Faraday.get("google.com") # => returns NoMethodError 
Faraday.get("http://google.com") # => this works 
```

The HTTP verb methods should raise an exception upon being given an improper URL as an argument. This exception should specify what URL format the method expects and what invalid URL formatting looks like as well. 
What files should I look at to start fixing this issue, thanks!

**Comment by gardnerapp** [comment] 2021-12-15 14:47
Sorry this error actually comes from Net::HTTP
net/http.rb:1679:in `addr_port': undefined method `include?' for nil:NilClass

**Comment by iMacTia** [comment] 2021-12-15 15:38
Thanks for double-checking @gardnerapp. I also tried this locally with Faraday v1.8 and I get a `Faraday::ConnectionFailed` error back instead of `NoMethodError`, so I'm not sure what's going on your side.
I'm not against adding some extra checks and useful messages though, so I'd welcome a PR that addresses that.

HTTP verb methods are dynamically defined in the [`connection`](https://github.com/lostisland/faraday/blob/main/lib/faraday/connection.rb) class and they internally all call the [`run_request`](https://github.com/lostisland/faraday/blob/main/lib/faraday/connection.rb#L432) method.

**Comment by JAugusto42** [comment] 2022-07-16 13:47
I was investigating this, in the `lib > faraday > adapter.rb` file, in the `connection` method i added a `raise`, but I think I need some help with the message and the best way to make sure this implementation is correct. I'll send you a PR so you can review.

**Comment by fchatterji** [comment] 2023-02-06 18:20
Hey @iMacTia, i looked at this issue as it seemed a good place to start contributing. Like you however I can't reproduce it, I just get a connection error. I think you can close it.

**Comment by iMacTia** [comment] 2023-02-06 22:05
@fchatterji thanks for the reminder! Closing it now on the basis that we were not able to reproduce it. Happy to reopen if someone can provide additional information!

**Closed** 2023-02-06 22:05 UTC
Labels: feature, good first issue

**Comment by bautrey37** [comment] 2023-02-07 12:36
I get this same error on faraday 2.7. I think the problem is when faraday is configured like this:


```
Faraday.new(
      url: nil,
	...
)
```

This happened to my code because of a configuration bug when the URL changes based off of environment. The error code that is received comes Net::HTTP, but it would make sense for faraday to catch this configuration problem and return a error message.

**Comment by iMacTia** [comment] 2023-02-07 13:26
@bautrey37 the problem is that what you showed above is not an incorrect configuration actually.
I'm not personally a fan of this (and it's definitely not recommended), but technically you can do the following:

```ruby
conn = Faraday.new(url: nil) do |f|
  # configure the connection with any middleware/adapter
  f.response :logger
end

# Now you can use the same connection to call different domains
conn.get('http://google.com')
conn.get('http://apple.com')
```

Also, I'm still unable to reproduce the issue with 2.7.4:

```ruby
conn = Faraday.new(url: nil) do |f|
  f.response :logger
end

# I was expecting this to fail given the domain is missing, but instead...
conn.get('/path')
# => Faraday::ConnectionFailed: Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)
```

As you can see, I still get a `Faraday::ConnectionFailed` 🤔
