### ISSUE TITLE
Faraday::Adapter::Test::Stubs is not thread safe

### ISSUE THREAD

**Issue by tchutw** [lostisland/faraday#1365] opened 2022-01-05 20:51 UTC
## Basic Info

* Faraday Version: 0.13.1 (via Debian 10 "Buster")
* Ruby Version: 2.5.5

(I'm aware this version is *quite* far behind the most recent version, but the sections of code I will try to highlight below appear to still be relevant, and the thread-unsafety should be verifiable by inspection.)

## Issue description
Encountered while investigating a low repro rate unit test failure (< 0.1%) in our build system.
The test would fail on rare occasion with a "no stubbed request for".. failure despite the mocked stubs being accurate for the test.

From code inspection, there appears to be a delete vs. iteration race that is possible when multiple threads are running against the same Test::Stubs, with the delete in match() with the "each" iteration in matches?:
```
         stub, meta = matches?(stack, path, headers, body)
          if stub
            consumed << stack.delete(stub)
            return stub, meta
          end
          matches?(consumed, path, headers, body)
```

```
        def matches?(stack, path, headers, body)
          stack.each do |stub|
            match_result, meta = stub.matches?(path, headers, body)
            return stub, meta if match_result
          end
          nil
        end
```

When the issue is hit it appears to be able to cause a request that should be matched to not have a Stub match.

## Steps to reproduce
Below is a snippet of code that I believe can be used to reproduce this issue. (Apologies for any sloppiness - I don't write in Ruby quite that often.) The snippet is meant to be similar to the unit test that was failing, with the project specific information simplified out.

The sizes of the arrays and the number of threads were increased to make the issue more likely in this example, and the sleep time was added for this purpose as well, but it still might need to be run a dozen times in order for the issue to be reproduced.

```
require 'faraday'

BASE_PATH = "/path/".freeze

def test
  @stubs = Faraday::Adapter::Test::Stubs.new
  @conn = Faraday.new do |builder|
    builder.adapter :test, @stubs
  end

  test_input = {
    'a' => Array(1..100),
    'b' => Array(101..200),
    'c' => Array(201..300),
    'd' => Array(301..400),
    'e' => Array(401..500),
    'f' => Array(501..600),
    'g' => Array(601..700),
    'h' => Array(701..800),
  }

  (1..800).each do |i|
    @stubs.get(BASE_PATH + i.to_s) {|env| [200, {}, {}]}
  end

  threads = []
  test_input.each_pair do |letter, numbers|
    threads << Thread.new do
      sleep(1)
      numbers.each do |n|
        begin
          r = @conn.get(BASE_PATH + n.to_s, {}, nil)
          unless r.status == 200
            raise "Unexpected response code"
          end
        rescue => e
          puts "Failure for #{n}: #{e}"
        end
      end
      puts "Done."
    end
  end

  threads.each {|thread| thread.join}
end
```

**Comment by iMacTia** [comment] 2022-01-11 09:41
Hi @tchutw, thanks for raising this and apologies for the slow reply.
I had a look at the code and yes, it totally makes sense.
As you already correctly pointed out, the issue is with the line `consumed << stack.delete(stub)`.
Since that line is not actually atomic, another thread might try to consume a request that is being deleted, before it makes it into the `consumed` array.

I believe this could be easily fixed with a `Monitor`, similarly to what we did for the [`middleware_registry`](https://github.com/lostisland/faraday/blob/main/lib/faraday/middleware_registry.rb).

The only thing is that we're now currently on Faraday 2.0.x as a major release, and even if we backported this change, it would only make sense to backport it to the 1.x branch (currently on 1.9.x).
Do you think you'll be able to upgrade your project to at least use Faraday 1.9?

**Comment by tchutw** [comment] 2022-01-12 05:07
Thanks for the response.

**Comment by tchutw** [comment] 2022-01-12 05:10
Oops. Misclicked the close button, sorry about that.

Thanks for the response.

We would be able to upgrade to a 2.0.x major release version, that is to say, we're not specifically locked into the same versions that Debian is using per se, but it's not really my decision to do so, so I couldn't say we will necessarily upgrade.

**Comment by iMacTia** [comment] 2022-01-12 11:35
@tchutw great, in that case I'll fix this in v2 to begin with and if you have issues upgrading we can always backport it later 👍

**Comment by iMacTia** [comment] 2022-01-12 15:57
@tchutw I've just merged a PR on the `main` branch that should fix the race condition.
I tried your script a few times and I couldn't reproduce the issue, but it would be great if you could have a look as well (maybe I was just lucky?)

**Comment by tchutw** [comment] 2022-01-12 18:03
@iMacTia As far as the code snippet goes, the way I was testing originally was running test() multiple times in a loop, maybe 50 times or up to 100 times. As you can see the code snippet just defines test but doesn't actually call it. I should have clarified in the original reporting text or just added an invocation to the bottom of the code snippet for the correct translation from test function to test file.

If that wasn't the problem with trying to reproduce the issue, let me know. For reference my hit rate with this version of the test was somewhere in the ballpark of 1 in 3.

**Comment by iMacTia** [comment] 2022-01-13 10:08
Sorry @tchutw, I should have been clearer.
I noticed your snippet was just creating the test method, and I actually run that _before_ my changes to successfully reproduce the issue. After my change, it seemed as if the problem was gone, but when I moved to a more powerful laptop, the issue popped up again (on this laptop, the issue is basically ALWAYS reproducible!).

So I went back to the code and created #1380.
With this new change, now your test function is always passing, even after tens of attempts 👍
Is there a chance you could give it a try yourself using the code in the PR before I merge it?

**Comment by tchutw** [comment] 2022-01-15 01:57
@iMacTia Alright, it appears that I completely misinterpreted what you meant to communicate.

Anyways, I tried it out on my end and I am no longer able to reproduce the issue with the PR code.

**Comment by iMacTia** [comment] 2022-01-15 08:58
@tchutw I most probably didn't express myself well enough 🙏 
Glad to hear the problem seems gone, I'll get the PR merged and ship a new release 👍 
As we mentioned above, please let me know if you can't use the new release and we can look into backporting this

**Closed** 2022-01-15 08:58 UTC
