### ISSUE TITLE
specifying ca_path doesn't seem to work with net::http

### ISSUE THREAD

**Issue by dougalcorn** [lostisland/faraday#371] opened 2014-04-24 13:23 UTC
It may be me, or it may be something in net::http, but I can't seem to verify a self-signed cert using ca_path on my Mac. I have a Rails app that is a client for an internal API accessed over https. In our various non-production environments we're using self-signed certificates. Rather than set `ssl: {verify: false}`, I figured I'd download the public self-signed certificates and store them with the project. I'm basing a lot of my work on this handy [command line reference for openssl](http://www.madboa.com/geek/openssl/).

Using `REMOTE_HOST` and `REMOTE_PORT=443` environment variables, I extracted the certificate like this:

``` shell
echo |\
openssl s_client -connect ${REMOTE_HOST}:${REMOTE_PORT} 2>&1 |\
sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > |\
config/certs/${REMOTE_HOST}.pem
```

I then symlinked that file to the fingerprint for the key:

``` shell
ln -s config/certs/${REMOTE_HOST}.pem `openssl x509 -noout -hash -in config/certs/${REMOTE_HOST}.pem`.0
```

From the command line, I can verify the certificate:

``` shell
$ echo |\
openssl s_client -CApath ./config/certs/ -connect ${REMOTE_HOST}:${REMOTE_PORT} 2>&1 |\
grep -i verify
verify return:1
    Verify return code: 0 (ok)
```

In my code, I think I'm doing the same thing:

``` ruby
ssl_options = { ca_path: Rails.root.join("config/certs/").to_s }
url = "https://#{ENV['REMOTE_HOST']}/"
connection = Faraday.new(url: url, :ssl => ssl_options)
auth_params = {uname: 'testing', pswd: 'testing'}
connection.post('/authenticate/upauth', auth_params)
```

This throws an error:

```
Faraday::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
    from /Users/dalcorn/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:918:in `connect'
    from /Users/dalcorn/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
    from /Users/dalcorn/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from /Users/dalcorn/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:918:in `connect'
    from /Users/dalcorn/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /Users/dalcorn/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from /Users/dalcorn/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/net/http.rb:1367:in `request'
    from /Users/dalcorn/devel/rails-project/vendor/ruby/2.0.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
    from /Users/dalcorn/devel/rails-project/vendor/ruby/2.0.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:39:in `call'
    from /Users/dalcorn/devel/rails-project/vendor/ruby/2.0.0/gems/faraday-0.9.0/lib/faraday/request/url_encoded.rb:15:in `call'
    from /Users/dalcorn/devel/rails-project/vendor/ruby/2.0.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
    from /Users/dalcorn/devel/rails-project/vendor/ruby/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
    from /Users/dalcorn/devel/rails-project/vendor/ruby/2.0.0/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'
    from (irb):5
```

I can see in [lib/faraday/adapter/net_http.rb](https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/net_http.rb) where `Faraday::Adapter::NetHttp#configure_ssl` simply copies the `ssl[:ca_path]` over to the http connection. I can also see that the `http.cert_store` is assigned an `OpenSSL::X509::Store` with the default paths. I've also tried calling `cert_store.add_path(ssl[:ca_path])`.  All of this results in the same failure to validate the self-signed certificate.

I'm pretty sure this is a bug in net::http, but I wasn't sure how to handle it. I thought I'd try here first and see what you guys thought.

**Comment by kennethkalmer** [comment] 2015-01-12 20:59
The Ruby maintainers are looking for some feedback on this issue reported on their bug tracker. If we can all help there then this issue can be closed. Thanks!

**Comment by coolaj86** [comment] 2015-03-25 05:51
Any updates?

**Comment by ml** [comment] 2015-05-01 13:11
As the guy says http://stackoverflow.com/a/10566822, there are a lot of things involved here. And you never know what system you're app's gonna run on. I'd do what @tomekw suggests - specify `ca_file` and bundle the file with your app or gem, so you're on the safe side.

**Comment by tomekw** [comment] 2015-05-01 13:29
In fact, I made it work with `ca_path` (it applies to RedHat based systems):

1. Check the `OPENSSLDIR` location:

    ``` bash
    $ openssl version -d
    OPENSSLDIR: "/etc/pki/tls"
    ```

2. Enter "certs" directory:

    ``` bash
    $ cd /etc/pki/tls/certs
    ```

3. Copy self-signed certificate to the "certs" directory:

    ``` bash
    $ cp /my/self/signed/cert.crt /etc/pki/tls/certs/my_self_signed_cert.crt
    ```

4. Ensure the self-signed certificate is in PEM format (output should contain certificate details):

    ``` bash
    $ openssl x509 -noout -text -in ./my_self_signed_cert.crt
    ```

5. Generate certificate hashes and create symlinks (".0" extension allows to avoid naming conflicts) for all self-signed certificates you plan to use:

    ``` bash
    $ ln -s my_self_signed_cert.crt `openssl x509 -noout -subject_hash -in ./my_self_signed_cert.crt`.0
    $ ln -s my_self_signed_cert.crt `openssl x509 -noout -subject_hash_old -in ./my_self_signed_cert.crt`.0 
    ```

6. Generate certificate hashes and create symlinks for CA bundle certificates:

    ``` bash
    $ ln -s ca-bundle.crt `openssl x509 -noout -subject_hash -in ./ca-bundle.crt`.0
    $ ln -s ca-bundle.crt `openssl x509 -noout -subject_hash_old -in ./ca-bundle.crt`.0
    ```

And this should work:

``` ruby
require "net/http"
require "net/https"
require "uri"
 
ca_path = "/etc/pki/tls/certs"
url = "https://example.com/status"
 
uri = URI.parse(url)
 
http = Net::HTTP.new(url.host, url.port)
http.use_ssl = true
http.ca_path = ca_path
http.verify_mode = OpenSSL::SSL::VERIFY_PEER
http.verify_depth = 5
 
request = Net::HTTP::Get.new(url.path)
response = http.request(request)
puts response.inspect
```

The most important here is `-subject_hash` and `-subject_hash_old` - it wasn't working because of different OpenSSL versions used to prepare hashes and to compile Ruby etc.

Also, in `ca_file` you have to have all certificates in the chain in correct order.

**Comment by ml** [comment] 2015-05-01 15:29
I needed this for a gem, so it needs to be independent from the operating system. What I did is I downloaded https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt and bundled it with the gem https://github.com/Syncano/syncano-ruby/commit/5887a2c41f94b3d6db50742012b987ca4bf4b440

**Comment by joost** [comment] 2015-12-01 16:04
I also had this issue on OSX.
Make sure your Ruby OpenSSL is a **similar version** as your system openssl!

```
> openssl version
OpenSSL 0.9.8zg 14 July 2015
>  ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.2d 9 Jul 2015
```

Above breaks `ca_path`. I had a ca_path with PEM files created using `c_rehash` (old version).

```
> which c_rehash 
/usr/bin/c_rehash
```

Fix it by installing a new openssl:
```
> brew install openssl
> brew link --force openssl
Linking /usr/local/Cellar/openssl/1.0.2d_1... 1548 symlinks created
```
Restart your shell here!
```
> openssl version
OpenSSL 1.0.2d 9 Jul 2015
> which c_rehash
/usr/local/bin/c_rehash
```
Now in your ca_path run the new version of `c_rehash`.

**Comment by akostadinov** [comment] 2016-03-14 20:26
I can confirm ca_path does work if you get proper cert hashes. If you include hashes for all system that you need to run on -  old and new, then it will always work.

**Comment by iMacTia** [comment] 2017-02-09 18:15
Closing this as clearly outside of Faraday's domain

**Closed by iMacTia** 2017-02-09 18:15 UTC
