### ISSUE TITLE
Rescue on Faraday.new

### ISSUE THREAD

**Issue by clubbavi** [lostisland/faraday#543] opened 2015-11-13 08:19 UTC
Hello,

I want a generic solution to rescue, when the connection is not established with the API.

Ex: 

```
begin
  connection = Faraday.new(:url => "API Path")
rescue Faraday::Error::ConnectionFailed => e
  redirect_to some_path
  return false
end
```

It works when I do specifically a GET or a POST:

```
begin
  conn = Faraday.new
  result = conn.get "API Path"
rescue Faraday::Error::ConnectionFailed => e
  redirect_to some_path
  return false
end
```

Any suggestions?

Thanks

**Comment by Zorbash** [comment] 2016-07-04 15:39
@clubbavi The suggestion below uses a Faraday middleware:

```ruby
class ErrorHandler < Faraday::Response::Middleware
  def on_complete(env)
   status = env[:status]
   return unless (400..599).include?(status) # do nothing on success

  # Add your generic handling code here
  end
end
```

Since this issue is not a bug and it does not need to be closed by a PR i think we should close it now.

**Comment by iMacTia** [comment] 2017-01-13 15:18
`connection = Faraday.new(:url => "API Path")` doesn't in fact open any connection.
It only set it up, the actual API call is performed only on subsequent `get`, `post`, etc...
This is why no exception is risen in that case

**Closed by iMacTia** 2017-01-13 15:18 UTC
