### ISSUE TITLE
ArgumentError: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by jaimeiniesta** [lostisland/faraday#476] opened 2015-04-30 10:01 UTC
We're getting this error using faraday 0.9.1, ruby 2.2.0 and OSX Yosemite:

``` ruby
> url = 'http://www.lemagit.fr/actualites/4500244568/SentinelOne-mise-sur-le-poste-de-travail-pour-detecter-les-attaques?asrc=EM_MDN_42264256&utm_medium=EM&utm_source=MDN&utm_campaign=20150428_SearchSecurity.fr%20:%20toute%20l%27information%20S%e9curit%e9%20-%20Avril%202015_'
 => "http://www.lemagit.fr/actualites/4500244568/SentinelOne-mise-sur-le-poste-de-travail-pour-detecter-les-attaques?asrc=EM_MDN_42264256&utm_medium=EM&utm_source=MDN&utm_campaign=20150428_SearchSecurity.fr%20:%20toute%20l%27information%20S%e9curit%e9%20-%20Avril%202015_"

> conn = Faraday.new(url: url)
 => #<Faraday::Connection:0x007fdf59ac04c8 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.9.1"}, @params={"asrc"=>"EM_MDN_42264256", "utm_medium"=>"EM", "utm_source"=>"MDN", "utm_campaign"=>"20150428_SearchSecurity.fr : toute l'information S\xE9curit\xE9 - Avril 2015_"}, @options=#<Faraday::RequestOptions (empty)>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x007fdf59ac0298 @handlers=[Faraday::Request::UrlEncoded, Faraday::Adapter::NetHttp]>, @url_prefix=#<URI::HTTP http://www.lemagit.fr/actualites/4500244568/SentinelOne-mise-sur-le-poste-de-travail-pour-detecter-les-attaques>, @proxy=nil>

> conn.get
ArgumentError: invalid byte sequence in US-ASCII
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/utils.rb:174:in `gsub'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/utils.rb:174:in `escape'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/parameters.rb:50:in `block in encode'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/parameters.rb:59:in `call'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/parameters.rb:59:in `block in encode'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/parameters.rb:57:in `each'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/parameters.rb:57:in `encode'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/utils.rb:153:in `to_query'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:407:in `build_exclusive_url'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:191:in `build_env'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
    from /Users/jaime/.rvm/gems/ruby-2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
    from (irb):14
    from /Users/jaime/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```

**Comment by luvtechno** [comment] 2015-08-06 14:46
Another example here 

```ruby
url = "http://transit.ekitan.com/norikae/NorikaeSearch?SFNAME=%94%92%8B%E0%91%E4&SFCODE=&STNAME=%8C%DC%94%BD%93c&STCODE=&SV1NAME=&SV1CODE=&MONTH=201508&DAY=06&HOUR=17&MIN=40&SR=0&btn_search.x=47&btn_search.y=21&RP=0&PN=5&EP=0&TP=0&AIR=0&TU1=1&TU2=1&TU3=1&CV=0&DC=0"
conn = Faraday.new(url: url)
conn.get
ArgumentError: invalid byte sequence in US-ASCII
from /opt/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/utils.rb:174:in `gsub'
```

Reproducible with faraday 0.9.1, ruby 2.2.2, on OSX Yosemite and Ubuntu 14.04.

**Comment by davoclavo** [comment] 2015-08-19 18:21
Calling `force_encoding(Encoding::BINARY)` on the `url` is a potential solution:

```rb
url = "http://example.com/search?q=%A0"

Faraday.get(url)
ArgumentError: invalid byte sequence in UTF-8

Faraday.get(url.force_encoding(Encoding::BINARY))
=> #<Faraday::Response:0x007fd8ca826ce8...
```

Probably this should be added [when the query params are unescaped](https://github.com/lostisland/faraday/blob/master/lib/faraday/utils.rb#L179) but would like to engage in a discussion before submitting a pull request.

```rb
def unescape(s) CGI.unescape s.force_encoding(Encoding::BINARY).to_s end
```

**Comment by mislav** [comment] 2015-08-20 23:44
Sorry this hasn't got any attention. @davoclavo Yes, it seems that the logical course of action would be to treat URL data as binary because we don't know which encoding was used for its parameters. Please submit a pull request with tests, thanks

**Comment by iMacTia** [comment] 2016-11-08 18:34
Closing for the same reason as #513

**Closed by iMacTia** 2016-11-08 18:34 UTC
Labels: bug

**Comment by jaimeiniesta** [comment] 2017-02-23 22:13
Sorry, this still fails in Faraday 0.11.0, just like in the first comment of this issue. Is this supposed to be fixed?

Thanks!

**Comment by iMacTia** [comment] 2017-02-23 22:53
Hi @jaimeiniesta,
no this issue have not been addressed, you can find more details on  https://github.com/lostisland/faraday/pull/513#issuecomment-254794047
