### ISSUE TITLE
Ruby 2.6 body size issue

### ISSUE THREAD

**Issue by adamof** [lostisland/faraday#842] opened 2019-01-07 16:27 UTC
## Basic Info

* Faraday Version: 0.15.4
* Ruby Version: 2.6.0

## Issue description
We use Faraday to send requests to an internal service of ours. We noticed that on big (large body) requests the request seems to be cut-off.

## Steps to reproduce
```ruby
headers = { 'Content-Type' => 'application/json' }
conn = Faraday.new(url: service_endpoint, headers: headers) do |faraday|
  faraday.request :json
  faraday.use Errors::ResponseMiddleware
  faraday.adapter :net_http
end

conn.post('endpoint', body) # body is a ruby Hash
```
We've compared this behaviour by sending different sizes of the body and confirming that the problem happens only on large bodies. 
The manifestation of the problem is seen in our service, where we see `ActionDispatch::ParamsParser::ParseError` errors.
Important to mention that this started happening after we upgraded to **Ruby 2.6**.

**Comment by adamof** [comment] 2019-01-08 08:48
Could be related to https://github.com/ruby/ruby/commit/7db24a6269c85313ccf57d601ccef684f2cdb4fa#diff-6db432a68fdb5a8610cebb37a60a2d47

**Comment by adamof** [comment] 2019-01-08 08:54
https://github.com/ruby/ruby/pull/2058

**Comment by iMacTia** [comment] 2019-01-08 15:38
Hi @adamof thanks for the heads-up.
From what I see, since the `Net::HTTP` adapter relies on Ruby's core library, the issues you linked could definitely be related.
I can see the issue has been fixed already on Ruby but is probably pending release.
Would you be able to test your code again using the patched Ruby and let me know if we can close this issue?

Thanks

**Comment by mensfeld** [comment] 2019-01-08 17:43
Or a quick patch for Faraday if you prefer:

```ruby
module NetHttpFaradayPatch
  def create_request(env)
    super.tap do |request|
      request.content_length = env[:body].size if env[:body].respond_to?(:read)
    end
  end
end

Faraday::Adapter::NetHttp.prepend(NetHttpFaradayPatch)
```

**Comment by iMacTia** [comment] 2019-01-08 17:43
Thanks for jumping in @mensfeld, I'll close this issue for now then assuming it's `Net::HTTP` issue.
Happy to reopen if that's not the case.

**Closed by iMacTia** 2019-01-08 17:43 UTC

**Comment by mensfeld** [comment] 2019-01-08 17:48
@iMacTia you could release a patch though. Many people will thank you for that.

**Comment by iMacTia** [comment] 2019-01-08 18:20
In these cases it’s usually better to wait for an upstream patch. People having issues with big payloads can monkey patch the code until then.

**Comment by mensfeld** [comment] 2019-01-08 18:49
@iMacTia shouldn't Faraday in that case block possibility to use it with 2.6.0 as the behavior is not predictable? I'm just saying, that a lot of people won't see this error until it hits them on production...

**Comment by adamof** [comment] 2019-01-09 08:50
I second what @mensfeld is saying about people being surprised on production. Also, it seems that there are two cases when things blow up:
- big bodies (our case)
- UTF-8 data

**Comment by iMacTia** [comment] 2019-01-09 10:24
I completely understand what you're saying guys, don't get me wrong. It's not like I want devs to have some hard time with this.

The fact is, this is not the only gem suffering from this issue as it's related to a Ruby bug, which has bean already raised and fixed. All we're waiting for now is the release of the fix.
When this usually happens, affected gems just wait for the fix to be released as otherwise everyone would need to release a temporary version of the gem and then release it again once the issue is fixed. It's just not worth it. Plus, there's no guarantee people will upgrade faraday at the same time as their Ruby, so this might not even fix the problem for everyone.

On the production surprise, I'm sorry but if you bump your Ruby version in production without first thoroughly testing in development or staging then I think you're being a bit too much optimistic 😅.
This kind of issues always happen upon a Ruby upgrade which is not a hotfix, that's why lots of devs usually wait for the 2.x.1 version before upgrading.

If the Ruby team delays the fix release and many others report this bug here, then I'll consider releasing a patch to contain the damage, otherwise as I said I'm sorry but it's just not worth it.

**Comment by adamof** [comment] 2019-01-09 10:33
> On the production surprise, I'm sorry but if you bump your Ruby version in production without first thoroughly testing in development or staging then I think you're being a bit too much optimistic 😅.
This kind of issues always happen upon a Ruby upgrade which is not a hotfix, that's why lots of devs usually wait for the 2.x.1 version before upgrading.

⚔️ touché 😄 

> If the Ruby team delays the fix release and many others report this bug here, then I'll consider releasing a patch to contain the damage, otherwise as I said I'm sorry but it's just not worth it.

Fair enough

**Comment by em77** [comment] 2019-01-16 16:17
@adamof What qualifies as a "big" body in the context of this issue?

**Comment by mensfeld** [comment] 2019-01-16 16:19
@em77 depends on the setup. If you want do a local reproduction you will need tens of megabytes of payload, but for a non-local env, I've seen problems with 16MB or less.

**Comment by mensfeld** [comment] 2019-01-31 10:46
FYI for anyone that might be interested: fixed in 2.6.1.

**Comment by milianoo** [comment] 2020-03-05 00:00
@mensfeld Thanks for the comment, after long-hours and many attempts, finally this solved it. 
Just to update the thread: 
I had issue with special characters in my content and also base64 image in the json content that was causing weird behaviour when content size was over a certain number. by using `body_stream` instead of `body` and setting the content-length using `bytesize` issue was resolved.

**Comment by mensfeld** [comment] 2020-03-05 10:52
@milianoo I would just recommend bumping to `2.6.1` instead of patching.
