### ISSUE TITLE
Faraday removes preconfigured URI from instance on requests

### ISSUE THREAD

**Issue by sameignatovich** [lostisland/faraday#1568] opened 2024-06-16 14:06 UTC
## Basic Info

* Faraday Version: 2.9.1
* Ruby Version: 3.3.3

## Issue description
When I tried to use API endpoints, where api key includes in URI, I found what Faraday removes by himself this key from basic url in instance:

```ruby
def get_me
  faraday_instance.get('/getMe')
end

def faraday_instance
  @faraday_instance ||= Faraday.new(
    url: "#{ENV.fetch('BOT_API_URL')}/bot#{ENV.fetch('BOT_API_TOKEN')}"
  )
end
```

```
irb(main):001> SomeApi.faraday_instance.url_prefix
=> #<URI::HTTP http://example.com/botSECRET_TOKEN>

irb(main):002> TelegramApi.get_me.env.url
=> #<URI::HTTP http://example.com/getMe>
```

I searched some explanation in documentation and found nothing. Is it expected behavior?

## Steps to reproduce
Look description

**Comment by yykamei** [comment] 2024-06-17 01:22
The URL string passed when initializing `Faraday::Connection` will be converted to Ruby's `URI` instance [here](https://github.com/lostisland/faraday/blob/4abafa5c66ce75bc2abbf0a5e7e98137dea91eb2/lib/faraday/utils.rb#L74).

If `get` receives the first argument, then it will be merged in [this code](https://github.com/lostisland/faraday/blob/4abafa5c66ce75bc2abbf0a5e7e98137dea91eb2/lib/faraday/connection.rb#L477) with `url` passed when initializing. [`URI#+`](https://ruby-doc.org/3.3.3/stdlibs/uri/URI/Generic.html#method-i-2B) will overwrite its URL prefix when the passed path is prefixed with `/`.


```ruby
irb(main):001> require 'uri'
=> true
irb(main):002> base = URI('https://example.com/abc/')
=> #<URI::HTTPS https://example.com/abc/>
irb(main):003> base + '/getMe'
=> #<URI::HTTPS https://example.com/getMe>
irb(main):004> base + 'getMe' # Without `/`, you can get expected result.
=> #<URI::HTTPS https://example.com/abc/getMe>
irb(main):005>
```

**Comment by iMacTia** [comment] 2024-06-17 09:48
As @yykamei said, the issue is that you're calling `faraday_instance.get('/getMe')` with a `/` prefix on the url.
That is basically a signal for Faraday to say "just call this path on top of the base URL DOMAIN, ignoring everything else.

If you want to keep the `/botSECRET_TOKEN` path you provided in the base URL and just append `/getMe` you can use `faraday_instance.get('getMe')`. Faraday will automatically add the missing `/` for you, don't worry!

**Closed by iMacTia** 2024-06-17 09:48 UTC
