### ISSUE TITLE
Faraday::Error: false is not registered on Faraday::Adapter

### ISSUE THREAD

**Issue by abhitrivedi** [lostisland/faraday#761] opened 2018-01-25 06:41 UTC
## Basic Info
Faraday intermittently errors on setting up middleware/adapter
* Faraday Version: 1.4.1
* Ruby Version: 2.4.0

## Issue description
I have an application that uses Faraday for external calls using typhoeus adapter. Every once a while (~1% of requests) faraday connection fails to initialize with the error:

`Faraday::Error: false is not registered on Faraday::Adapter`

Here is how the connection is set up:
```ruby

# connection_helper.rb
require 'faraday'
require 'typhoeus'
require 'typhoeus/adapters/faraday'
require 'faraday-http-cache'

module ConnectionHelper
  def connection(host)
    Faraday.new(url: host) do |conn|
      conn.use :http_cache, store: CACHE_STORE, shared_cache: false
      conn.adapter :typhoeus
    end
  end
end


# foo_service.rb
class MyService
  class << self
    include ConnectionHelper

    def get(host, path)
      response = connection(host).get(path)
      handle_error(response)
      response.body
    end
  end
end
```

## Steps to reproduce
Sorry, I cannot reproduce this error locally, but it's painfully consistent (yet random) in cloud environments.

**Comment by abhitrivedi** [comment] 2018-01-25 06:52
Here's the stacktrace:
```
Faraday::Error: false is not registered on Faraday::Adapter
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday.rb:191:in `lookup_middleware'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:228:in `use_symbol'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:101:in `adapter'
./services/connection_helper.rb:23:in `block in connection'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:89:in `initialize'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday.rb:70:in `new'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday.rb:70:in `new'
./services/connection_helper.rb:13:in `connection'
```

**Comment by abhitrivedi** [comment] 2018-01-26 06:06
Changing the adapter statement to `conn.use Faraday::Adapter::Typhoeus` fixes the error above, but now a new error shows up:
```
NameError: wrong constant name false
./bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:  261:in `const_get'
./bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:  261:in `block in constantize'
./bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:  259:in `each'
./bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:  259:in `inject'
./bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/inflector/methods.rb:  259:in `constantize'
./bundle/ruby/2.4.0/gems/activesupport-4.2.9/lib/active_support/core_ext/string/inflections.rb:   66:in `constantize'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:   20:in `block in <class
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:   34:in `klass'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:  224:in `is_adapter?'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:  213:in `block in adapter_set?'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:  213:in `any?'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:  213:in `adapter_set?'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:   87:in `use'
./services/connection_helper.rb:   21:in `block in connection'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday/connection.rb:   89:in `initialize'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday.rb:   70:in `new'
./bundle/ruby/2.4.0/gems/faraday-0.14.0/lib/faraday.rb:   70:in `new'
./services/connection_helper.rb:   17:in `connection'
```

I can repro this error locally by running the server and repeatedly make calls until the error happens, sometimes takes seconds, sometimes minutes.

About the app, I have a Rails 4.2.9 server + Roda 3.4.0 middleware running on puma.

**Comment by iMacTia** [comment] 2018-01-26 09:08
Hi @abhitrivedi sorry I didn't have time to look into this yesterday but I'll do my best to have a look today.
In the meantime, can you try to force Faraday to version 0.13.1 if possible and let know if you still see the error? (I understand you'll need some time to check this as the error appears at random).

**Comment by iMacTia** [comment] 2018-01-26 11:07
@abhitrivedi Also, do you get the same error if you remove `:http_cache` from the stack?
Sorry for asking you to run additional tests, it's just I might be missing something in my setup.

**Comment by iMacTia** [comment] 2018-01-26 16:21
@abhitrivedi I've spent some time on this today, and I found something, but still couldn't get to the base of the issue.
First of all, the exceptions we see.
I was able to get the first one by passing `false` to `.use`:

```ruby
Faraday.new do |conn|
  conn.use false
  conn.adapter :typhoeus
end
# => NameError: wrong constant name false
```

And the second one can be reproduced by doing:

```ruby
Faraday.new do |conn|
  conn.adapter false
end
# => Faraday::Error: false is not registered on Faraday::Adapter
```

That said, seems like you're somehow passing `false` at some point in the stack (notice in the second example that this works also for other lines, not just the adapter).
In order to help any further I'll need to see the exact implementation, as I suppose the code you provided was simplified a bit.

**Comment by abhitrivedi** [comment] 2018-01-26 20:29
Thanks @iMacTia. I'll try to get those test results in a couple of days. The middleware and adapter are hardcoded in the file so Im not sure how `false` could passed in the stack. 
It's interesting to note that the `NameError: wrong constant name false` error happens either while initializing a `Faraday::Connection` or while making the request itself, i.e.:
```ruby
conn = ConnectionHelper.connection #=> error location #1
response = conn.get(service_path) #=> error location #2
```
It's sporadic and random nature somehow reminds me of thread safety issues (since puma is using processes and threads together), but Im not sure whether multi-threading is truly the root cause.

I'll get that data and let you know, thanks.

**Comment by raydog153** [comment] 2018-01-28 18:13
I'm having very similar issue...for me the error is:
`wrong argument type FalseClass (expected Proc)`

It seems to only show up in unit tests within our build machines but finally was able to reproduce it fairly consistent locally. I'm using the default adapter and very simple setup. For every API call I make I create a new Faraday connection, even if it is for the same domain. If this the correct way? I feel like there is something that is getting re-used and garbage collected and that is when this happens.

I reproduced using :net_http_persistent and :net_http adapters. As well as under version 0.14.0 and 0.13.1. There is no way I am passing in a FalseClass as I am using symbol for the adapter.

Stack trace for 0.13.1:
`
wrong argument type FalseClass (expected Proc)
/Users/rboutotte/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:101:in `adapter'
/Users/rboutotte/firstfuel/WORKBENCH/frontend/gems/ff-api/lib/ff/api/faraday_requestor.rb:18:in `block in init_connection'
/Users/rboutotte/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:88:in `initialize'
/Users/rboutotte/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday.rb:67:in `new'
/Users/rboutotte/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday.rb:67:in `new'
/Users/rboutotte/firstfuel/WORKBENCH/frontend/gems/ff-api/lib/ff/api/faraday_requestor.rb:10:in `init_connection'
`

Here is my code for init_connection, :
`
  def init_connection(method, uri, multipart_request)
      Faraday.new("#{uri.scheme}://#{uri.host}:#{uri.port}") do |faraday| # Line 10
        if multipart_request
          faraday.use Faraday::Request::UrlEncoded
          faraday.use Faraday::Request::Multipart
        end
        if [:post, :put].include?(method)
          faraday.use Faraday::Request::UrlEncoded
        end
        faraday.adapter(:net_http) # Line 18
      end
  end
`

**Comment by raydog153** [comment] 2018-01-29 18:05
FYI: In trying to fix this my co-workers tried different ruby versions. We can no longer reproduce the error "wrong argument type FalseClass" using ruby version != 2.4.0. We tried 2.3.3, 2.4.1, 2.4.3, 2.5.0 and this issue does not show up, but reverting back to 2.4.0 the issues happens.

@abhitrivedi I am not sure what the root cause is within 2.4.0, but try any other version of ruby to see if it fixes your issue as well. It would be nice if someone can go thru ruby 2.4.0 changes to determine what was causing this issue that seems to be fixed in 2.4.1.

**Comment by abhitrivedi** [comment] 2018-01-29 19:58
Interesting. Thanks @raydog153 I'll try it out.

**Comment by iMacTia** [comment] 2018-01-29 22:25
Thanks @raydog153!
Your details really seem related and might explain why I still wasn't able to reproduce this locally, as I'm using Ruby 2.4.1.
I erroneously assumed this would be ok as it's just a minor version higher, but from what you say that doesn't seem the case!
Thanks to you, your colleague and @abhitrivedi for looking into this.
I'm sorry I don't have much time to spend on this in these days but please let me know as soon as you find something.
I'm happy to release a fix for Faraday to eventually mitigate this issue once we understand what causes it

**Comment by iMacTia** [comment] 2018-01-29 22:31
@abhitrivedi @raydog153 Apparently this is a known Ruby 2.4.0 bug: https://bugs.ruby-lang.org/issues/13107

It happens when using `def_delegators` (which are used in Faraday).
I'll see if there's any fix we can apply on our side, but of course the easiest solution is to upgrade to Ruby 2.4.1 where this bug have been fixed.

**Comment by iMacTia** [comment] 2018-02-04 11:20
Couldn't find anything with a quick search, I'm closing this down with the recommendation to upgrade to Ruby 2.4.1 if you encounter this bug.
Happy to reopen if someone has an idea for a workaround

**Closed by iMacTia** 2018-02-04 11:20 UTC
Labels: unconfirmed

**Comment by 9mm** [comment] 2023-04-10 02:34
I'm getting this on ruby 3.2.2

**Comment by iMacTia** [comment] 2023-04-11 08:16
@9mm this might be a regression in Ruby 3.2.2, do you get the error while using other Ruby versions?

**Comment by 9mm** [comment] 2023-04-11 16:49
@iMacTia actually I misread the word false, this is my exact error that I'm getting:

```Faraday::Error: :typhoeus is not registered on Faraday::Adapter```

I'm getting this when trying to use `SearchKick` with typhoeus per their instructions: https://github.com/ankane/searchkick#persistent-http-connections

They mention to only add `typhoeus` to the gemfile by itself, and when I reindex the database (ie searchkick uses faraday/typheous to connect) it throws the error above

if I add the faraday-typheous gem to the gemfile, then it works without any error, but this appears to be unexpected behavior as the owner of searchkick is confident that its not needed

https://github.com/ankane/searchkick/issues/1623

**Comment by iMacTia** [comment] 2023-04-12 16:30
That normally means that `typhoeus` was not registered as an adapter.
There can be multiple reasons for this. Faraday originally bundled and registered typhoeus itself, then as of Faraday 2.0 this is no longer the case and there's now a [standalone adapter](https://github.com/dleavitt/faraday-typhoeus).

I'm unsure how `searchkick` works, but it's worth checking if they support Faraday 2.0.
If they don't they might still be relying on the out-of-the-box adapter in v1.x, which won't work in v2.0.
If you'd still like to use Faraday 2.0 (which I definitely recommend) you could try adding the `faraday-typhoeus` gem explicitly to your gemfile as that should be compatible with Faraday 2.0.

If that doesn't work and you still have questions, please open a separate issue as I'm now pretty sure this is unrelated to this thread 😄

**Comment by ahmadgandar** [comment] 2023-04-12 17:10
Unscribe

Pada tanggal Rab, 12 Apr 2023 23.30, Matt ***@***.***>
menulis:
