### ISSUE TITLE
Differences between adapters 

### ISSUE THREAD

**Issue by jurriaan** [lostisland/faraday#736] opened 2017-10-12 13:45 UTC
While browsing through the adapters Faraday offers to find how I can best handle persistent connections and I noticed that some adapters reuse the same session/connection pool, and some don't.

I first tried Patron. Patron seemed to work just fine handling persistent connections. This is due to the adapter reusing the same session for all requests, and thus being able to reuse connections.
After a while we noticed weird errors (#626) which occur because as documented in the Patron documentation the Session object is *not* thread-safe. While this is fine and your documentation does not state Faraday is or should be thread-safe, I started looking for an alternative to Patron which also promised persistent connections and is thread-safe.

Net-http-persistent is one of these alternatives which I started looking into. Especially since their documentation states: 'Thread-safe persistent connections with Net::HTTP', which would fix my issues with persistency and thread-safety.

But when trying this adapter I noticed it does not use persistent connections out of the box. This is due to a new instance of the Net::HTTP::Persistent class being created for every request. See https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/net_http_persistent.rb#L10.
This effectively makes the connection pool used within Net::HTTP::Persistent useless.

I saw the same behaviour for the Excon adapter. Which offers a persistent option, but a new instance of Excon is created for all requests.

So my question here is, what is your policy regarding adapters. I find it quite interesting that the only adapter that offers persistent connections (Patron) is not thread safe, and other adapters where it is possible to use persistence it is not possible to use it since the adapter creates a new instance for every connection.

**Comment by johnl** [comment] 2017-10-16 16:08
I can confirm that Net::HTTP::Persistent doesn't seem to actually use persistent connections - I'm using strace to confirm and it opens a new connection for every request!

**Comment by iMacTia** [comment] 2017-10-18 15:01
Hi @jurriaan thanks for reporting this!

Indeed the whole idea behind having a `net_http_persistent` adapter should be about having the same connection open all the time. If that's not the case, that might be an adapter implementation issue.
Unfortunately people have been asking to add adapters to Faraday over time and the core team was not always very knowledgeable about the library being used.
This is one of the reason why we're pushing adapters out of Faraday going towards version 1.0, where other people can take care of maintaining and updating them over time.

So to answer your question, each adapter is completely independent from the others and should offer the functionalities that the underlying library offers, always maintaining compatibility with the Faraday API. In this case it's fair to say that a clear feature of `net_http_persistent` is not being provided by the adapter, even though I see no problem in doing that.

### Great, so what do we do now?

I'm not a `net_http_persistent` adapter user so I never noticed this issue, but I'm happy to review a PR that tries to fix this (and maybe another one for Excon as well?).

Alternatively, you can go down the other way and build your own `faraday-net-http-persistent` gem which will host the adapter, or even ask the net-http-persistent team to include the adapter into their gem as Typhoeus does.

I was recently asked about `net-http-2` and it's integration with Faraday, you can see my reply here: https://github.com/lostisland/faraday/issues/734#issuecomment-334513030. I would suggest you exactly the same things!

I'm closing this Issue for now but once you decide how to move forward please feel free to open a separate issue/pr for each adapter.

Thanks

**Closed by iMacTia** 2017-10-18 15:01 UTC
